# Generated by Django 4.2.17 on 2025-06-29 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0011_remove_lecture_description_coursesection_description'),
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLearningStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_enrollments', models.PositiveIntegerField(default=0)),
                ('completed_courses', models.PositiveIntegerField(default=0)),
                ('total_learning_hours', models.FloatField(default=0)),
                ('current_streak_days', models.PositiveIntegerField(default=0)),
                ('longest_streak_days', models.PositiveIntegerField(default=0)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'User Learning Statistics',
            },
        ),
        migrations.AlterModelOptions(
            name='courseprogress',
            options={'verbose_name_plural': 'Course Progresses'},
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='last_lecture_accessed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.lecture'),
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='completed_lectures',
            field=models.ManyToManyField(blank=True, related_name='completed_by', to='courses.lecture'),
        ),
        migrations.AddIndex(
            model_name='courseprogress',
            index=models.Index(fields=['enrollment'], name='enrollments_enrollm_284e4e_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'course'], name='enrollments_student_dd373e_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'completed'], name='enrollments_student_1b32dd_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['progress_percentage'], name='enrollments_progres_e7e27b_idx'),
        ),
        migrations.AddField(
            model_name='userlearningstats',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_stats', to=settings.AUTH_USER_MODEL),
        ),
    ]
