# Generated by Django 4.2.17 on 2025-06-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_lecture_description_coursesection_description'),
        ('enrollments', '0002_userlearningstats_alter_courseprogress_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlearningstats',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='courseprogress',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='courseprogress',
            name='enrollments_enrollm_284e4e_idx',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='enrollments_student_dd373e_idx',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='enrollments_student_1b32dd_idx',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='enrollments_progres_e7e27b_idx',
        ),
        migrations.RemoveField(
            model_name='courseprogress',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='last_lecture_accessed',
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='completed_lectures',
            field=models.ManyToManyField(blank=True, to='courses.lecture'),
        ),
        migrations.DeleteModel(
            name='UserLearningStats',
        ),
    ]
