# Generated by Django 4.2.17 on 2025-07-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_enrollment_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='time_spent_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
