# Generated by Django 4.2.17 on 2025-06-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
