# Generated by Django 4.2.17 on 2025-06-24 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planning', '0002_contentreleaserule_contentreleaseschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentreleaseschedule',
            name='created_by',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='created_schedules', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
