# Generated by Django 4.2.17 on 2025-06-25 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planning', '0004_alter_contentreleaseschedule_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentreleaserule',
            name='created_by',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='created_release_rules', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
