# Generated by Django 4.2.17 on 2025-06-25 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_contentreleaserule_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentreleaserule',
            name='created_by',
        ),
    ]
