# Generated by Django 4.2.17 on 2025-07-16 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_contentreleaserule_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentreleaserule',
            name='is_manually_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentreleaserule',
            name='required_completion_item',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contentreleaserule',
            name='required_progress_percentage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentreleaserule',
            name='trigger',
            field=models.CharField(choices=[('enrollment', 'Upon Enrollment'), ('date', 'Specific Date'), ('completion', 'After Previous Completion'), ('progress', 'Progress-based'), ('manual', 'Manual Release')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprogressoverride',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_overrides', to='planning.contentreleaserule'),
        ),
    ]
