# Generated by Django 4.2.17 on 2025-07-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_contentreleaserule_is_manually_unlocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentreleaserule',
            name='required_quiz_score',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum score percentage required for quiz performance trigger', null=True),
        ),
        migrations.AlterField(
            model_name='contentreleaserule',
            name='trigger',
            field=models.CharField(choices=[('enrollment', 'Upon Enrollment'), ('date', 'Specific Date'), ('completion', 'After Previous Completion'), ('progress', 'Progress-based'), ('manual', 'Manual Release'), ('quiz_completion', 'Quiz Completion'), ('quiz_performance', 'Quiz Performance')], max_length=20),
        ),
    ]
