# Generated by Django 4.2.17 on 2025-07-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0009_contentreleaserule_required_quiz_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('course', 'Course Related'), ('personal', 'Personal'), ('meeting', 'Meeting'), ('reminder', 'Reminder'), ('deadline', 'Deadline'), ('publishing', 'Publishing'), ('writing', 'Writing'), ('review', 'Review'), ('editing', 'Editing')], max_length=20),
        ),
    ]
