# Generated by Django 4.2.17 on 2025-07-20 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EbookTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('COVER', 'Cover'), ('CHAPTER', 'Chapter'), ('FULL', 'Full eBook')], default='FULL', max_length=10)),
                ('thumbnail', models.ImageField(upload_to='ebook_templates/thumbnails/')),
                ('is_default', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='ebook_templates/covers/')),
                ('styles', models.JSONField(default=dict)),
                ('structure', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('styles', models.JSONField(default=dict)),
                ('structure', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='templates.ebooktemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ebooktemplate',
            index=models.Index(fields=['type'], name='templates_e_type_3af68e_idx'),
        ),
        migrations.AddIndex(
            model_name='ebooktemplate',
            index=models.Index(fields=['is_default'], name='templates_e_is_defa_ab0c53_idx'),
        ),
        migrations.AddIndex(
            model_name='ebooktemplate',
            index=models.Index(fields=['is_premium'], name='templates_e_is_prem_c924e7_idx'),
        ),
    ]
