# Generated by Django 4.2.17 on 2025-06-18 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='course_thumbnails/'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lectureresource',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lectureresource',
            name='external_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lectureresource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lecture_resources/'),
        ),
        migrations.AddField(
            model_name='lectureresource',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lectureresource',
            name='resource_type',
            field=models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('link', 'Link'), ('document', 'Document'), ('image', 'Image')], default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='banner_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.coursecategory'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lectureresource',
            name='kind',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('pdf', 'PDF'), ('link', 'Link'), ('document', 'Document'), ('image', 'Image')], max_length=10),
        ),
        migrations.AlterField(
            model_name='lectureresource',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
