# Generated by Django 4.2.17 on 2025-06-27 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursecategory_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecategory',
            name='is_active',
        ),
    ]
