# Generated by Django 4.2.17 on 2025-06-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_coursecategory_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
