# Generated by Django 4.2.17 on 2025-06-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursecategory_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Courses that must be completed before this course', related_name='prerequisite_for', to='courses.course'),
        ),
    ]
