# Generated by Django 4.2.17 on 2025-06-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='what_you_will_learn',
            field=models.TextField(blank=True, null=True),
        ),
    ]
