# Generated by Django 4.2.17 on 2025-06-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_what_you_will_learn'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='who_is_this_for',
            field=models.TextField(blank=True, null=True),
        ),
    ]
