# Generated by Django 4.2.17 on 2025-06-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_who_is_this_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_available',
            field=models.BooleanField(default=False),
        ),
    ]
