# Generated by Django 4.2.17 on 2025-06-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_certificate_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lifetime_access',
            field=models.BooleanField(default=True),
        ),
    ]
