# Generated by Django 4.2.17 on 2025-06-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_lecture_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='description',
        ),
        migrations.AddField(
            model_name='coursesection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
