# Generated by Django 4.2.17 on 2025-07-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_lecture_description_coursesection_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
