# Generated by Django 4.2.17 on 2025-07-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('INSTRUCTOR', 'Instructor'), ('STUDENT', 'Student'), ('SUPPORT_AGENT', 'Support Agent'), ('EBOOK_CREATOR', 'Ebook Creator'), ('PREMIUM_MEMBER', 'Premium Member')], default='STUDENT', max_length=15),
        ),
    ]
