# Generated by Django 4.2.17 on 2025-07-20 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EbookCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('AUTHOR', 'Author'), ('EDITOR', 'Editor'), ('REVIEWER', 'Reviewer')], max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='EbookProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='ebook_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebooks', to=settings.AUTH_USER_MODEL)),
                ('collaborators', models.ManyToManyField(related_name='collaborating_ebooks', through='ebooks.EbookCollaborator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EbookExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('EPUB', 'EPUB'), ('MOBI', 'MOBI')], max_length=5)),
                ('file', models.FileField(upload_to='ebook_exports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(max_length=20)),
                ('file_size', models.PositiveIntegerField()),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='ebooks.ebookproject')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'get_latest_by': 'generated_at',
            },
        ),
        migrations.AddField(
            model_name='ebookcollaborator',
            name='ebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebooks.ebookproject'),
        ),
        migrations.AddField(
            model_name='ebookcollaborator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.JSONField(default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='ebooks.ebookproject')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='ebookproject',
            index=models.Index(fields=['status'], name='ebooks_eboo_status_ad939b_idx'),
        ),
        migrations.AddIndex(
            model_name='ebookproject',
            index=models.Index(fields=['author'], name='ebooks_eboo_author__ba082c_idx'),
        ),
        migrations.AddIndex(
            model_name='ebookproject',
            index=models.Index(fields=['created_at'], name='ebooks_eboo_created_dce06c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ebookcollaborator',
            unique_together={('ebook', 'user')},
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['ebook', 'order'], name='ebooks_chap_ebook_i_d3609a_idx'),
        ),
    ]
