# Generated by Django 4.2.17 on 2025-07-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebookproject',
            name='template_structure',
            field=models.JSONField(blank=True, default=dict, help_text='Applied template structure settings'),
        ),
        migrations.AddField(
            model_name='ebookproject',
            name='template_styles',
            field=models.JSONField(blank=True, default=dict, help_text='Applied template styles (typography, colors, layout)'),
        ),
    ]
